[versions]
compose = "1.5.4"
compose-compiler = "1.5.8"
activityCompose = "1.8.2"
agp = "8.2.1"
appcompat = "1.6.1"
coilCompose = "2.5.0"
constraintlayoutCompose = "1.0.1"
coreKtx = "1.12.0"
espressoCore = "3.5.1"
jetlime = "1.0.4"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.22"
ktlint = "12.1.0"
lifecycleRuntimeKtx = "2.7.0"
material = "1.11.0"
materialVersion = "1.5.4"
multiFab = "1.2"
vanniktech = "0.27.0"

[libraries]
# Android
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }

# Android Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
multi-fab = { module = "academy.compose.companion:multi-fab", version.ref = "multiFab" }
jetlime = { module = "io.github.pushpalroy:jetlime", version.ref = "jetlime" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
nexus-vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }