[versions]
composeBom = "2024.03.00"
compose-compiler = "1.5.10"
activityCompose = "1.8.2"
agp = "8.2.2"
coreKtx = "1.12.0"
jetlime = "2.1.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.22"
kotlinxCollectionsImmutable = "0.3.7"
lifecycleRuntimeKtx = "2.7.0"
truth = "1.3.0"
vanniktech = "0.27.0"
dokka = "1.9.10"
spotless = "6.25.0"
androidxTest = "1.5.2"

[libraries]
# Android
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }

# Compose
# BOM
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom"}
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Not in BOM
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }

# Others
truth = { module = "com.google.truth:truth", version.ref = "truth" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
jetlime = { module = "io.github.pushpalroy:jetlime", version.ref = "jetlime" }
junit = { module = "junit:junit", version.ref = "junit" }
dokka-android = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokka"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nexus-vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"}
spotless = { id = "com.diffplug.spotless", version.ref = "spotless"}