name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  buildAndroid:
    name: Build Android
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Java and Gradle
      - name: Java and Gradle set up
        uses: ./.github/workflows/setup/java-setup

      # Grant execute permission for script
      - name: Grant execute permission for script
        id: grant_script_permission
        shell: bash
        run: chmod +x ./scripts/build_android.sh

      # Build and verify Android
      - name: Build and verify Android
        run: ./scripts/build_android.sh

  buildiOS:
    name: Build iOS
    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Java and Gradle
      - name: Java and Gradle set up
        uses: ./.github/workflows/setup/java-setup

      # Grant execute permission for script
      - name: Grant execute permission for script
        id: grant_script_permission
        shell: bash
        run: chmod +x ./scripts/build_android.sh

      # Setup iOS
      - name: iOS set up
        uses: ./.github/workflows/setup/ios-setup

      # Build iOS app
      - name: Build iOS app
        id: build_ios_debug
        run: xcodebuild build -workspace sample/iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphonesimulator -verbose

  buildWeb:
    name: Build Web
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Java and Gradle
      - name: Java and Gradle set up
        uses: ./.github/workflows/setup/java-setup

      # Grant execute permission for script
      - name: Grant execute permission for script
        id: grant_script_permission
        shell: bash
        run: chmod +x ./scripts/build_web.sh

      # Build and verify Web
      - name: Build and verify Web
        run: ./scripts/build_web.sh

  buildMacOS:
    name: Build MacOS
    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Java and Gradle
      - name: Java and Gradle set up
        uses: ./.github/workflows/setup/java-setup

      # Grant execute permission for script
      - name: Grant execute permission for script
        id: grant_script_permission
        shell: bash
        run: chmod +x ./scripts/build_macos.sh

      # Build and verify MacOS
      - name: Build and verify MacOS
        run: ./scripts/build_macos.sh