name: Check PR

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Java
      - name: Java set up
        uses: ./.github/workflows/composite

      # Setup Gradle
      - name: Set up Gradle
        id: set_up_gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: assembleDebug spotlessCheck